# Generated by Django 6.0.4 on 2026-05-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patients_genotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='current_complaints',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
    ]
